data <- read.csv(file="bigDataFromNonResized_removedTwice.csv", head=FALSE, sep="\t")
summary(data)
glmBinomial <- glm(data$V1 ~ data$V2 + data$V3 + data$V4 + data$V5 + data$V6 + data$V7 + data$V8 + data$V9 + data$V10 + data$V11 + data$V12 + data$V13, family = binomial())
anova(glmBinomial)
summary(glmBinomial)
rm(glmBinomial)
glmPoisson <- glm(data$V1 ~ data$V2 + data$V3 + data$V4 + data$V5 + data$V6 + data$V7 + data$V8 + data$V9 + data$V10 + data$V11 + data$V12 + data$V13, family = poisson())
anova(glmPoisson)
summary(glmPoisson)
rm(glmPoisson)
require(rpart)
treePred <- rpart(data$V1 ~ data$V2 + data$V3 + data$V4 + data$V5 + data$V6 + data$V7 + data$V8 + data$V9 + data$V10 + data$V11 + data$V12 + data$V13)
plot(treePred)
text(treePred, use.n = TRUE)
rm(treePred)
1-pchisq(219574,318288)