myData <- read.csv(file="bigData_RemovedThree.csv", head=FALSE, sep="\t")
summary(myData)
glmBinomial <- glm(V1 ~ ., family = binomial(), data = myData)
anova(glmBinomial)
summary(glmBinomial)
rm(glmBinomial)
glmPoisson <- glm(V1 ~., family = poisson(), data = myData)
anova(glmPoisson)
summary(glmPoisson)
rm(glmPoisson)
require(rpart)
treePred <- rpart(V1 ~ ., data = myData)
plot(treePred)
text(treePred, use.n = TRUE)
rm(treePred)
1-pchisq(219574,318288)